#!/usr/bin/env python3
# -*- coding: utf-8 -*-
from __future__ import annotations

"""
common.py — shared utilities for Tools/ scripts.

Auto-generated by the LLM Wiki agent. Provides:

  Path constants:
    REPO_ROOT, WIKI_DIR, RAW_DIR, LOG_FILE, INDEX_FILE, OVERVIEW_FILE, GRAPH_DIR

  I/O helpers:
    read_file(path)          — read text with utf-8 fallback
    write_file(path, content)— atomic utf-8 write
    ensure_utf8()            — reconfigure stdout/stderr to utf-8 (Windows-safe)
    init_env()               — call ensure_utf8() + put Tools/ on sys.path

  Content helpers:
    extract_wikilinks(text)  — return list of [[WikiLink]] targets
    all_wiki_pages()         — return list[Path] of all wiki .md files (excl. index/log/lint-report)
    append_log(entry)        — prepend a timestamped entry to wiki/log.md

  Hashing:
    sha256_short(content)    — 8-char hex digest
    sha256_full(content)     — full 64-char hex digest

  LLM:
    call_llm(prompt, ...)    — wrapper around opencode CLI (returns text).
                               If opencode not on PATH, raises NotImplementedError.
"""

import os
import sys
import re
import hashlib
import tempfile
import shutil
import subprocess
from datetime import date
from pathlib import Path
from typing import Any

# ─────────────────────────────────────────────────────────────────────
# Path constants
# ─────────────────────────────────────────────────────────────────────
TOOLS_DIR = Path(__file__).resolve().parent
REPO_ROOT = TOOLS_DIR.parent

WIKI_DIR = REPO_ROOT / "Wiki"
RAW_DIR = REPO_ROOT / "Raw"
GRAPH_DIR = REPO_ROOT / "Graph"

LOG_FILE = WIKI_DIR / "log.md"
INDEX_FILE = WIKI_DIR / "index.md"
OVERVIEW_FILE = WIKI_DIR / "overview.md"


# ─────────────────────────────────────────────────────────────────────
# Environment helpers
# ─────────────────────────────────────────────────────────────────────
def ensure_utf8() -> None:
    """Reconfigure stdout/stderr to utf-8 (Windows console default is GBK)."""
    for stream_name in ("stdout", "stderr"):
        stream = getattr(sys, stream_name, None)
        if stream is None:
            continue
        try:
            stream.reconfigure(encoding="utf-8", errors="replace")  # type: ignore[attr-defined]
        except (AttributeError, ValueError):
            pass


def init_env() -> None:
    """Initialize a clean env for Tools/ scripts: utf-8 + Tools/ on sys.path.

    Idempotent — safe to call from every entry point.
    """
    ensure_utf8()
    tools = str(TOOLS_DIR)
    if tools not in sys.path:
        sys.path.insert(0, tools)


# ─────────────────────────────────────────────────────────────────────
# File I/O
# ─────────────────────────────────────────────────────────────────────
def read_file(path: os.PathLike | str) -> str:
    """Read a text file as utf-8 with permissive error handling.

    Returns "" if the file does not exist or cannot be decoded.
    """
    p = Path(path)
    if not p.exists():
        return ""
    try:
        return p.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return p.read_text(encoding="utf-8", errors="replace")


def write_file(path: os.PathLike | str, content: str) -> None:
    """Atomically write `content` to `path` as utf-8.

    Creates parent dirs as needed. Uses a temp file + os.replace to avoid
    partial writes on crash.
    """
    p = Path(path)
    p.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w",
        encoding="utf-8",
        newline="\n",
        dir=str(p.parent),
        prefix=f".{p.name}.",
        suffix=".tmp",
        delete=False,
    ) as tmp:
        tmp.write(content)
        tmp_path = Path(tmp.name)
    shutil.move(str(tmp_path), str(p))


# ─────────────────────────────────────────────────────────────────────
# Wiki content helpers
# ─────────────────────────────────────────────────────────────────────
_WIKILINK_RE = re.compile(r"\[\[([^\]\|]+?)(?:\|[^\]]*)?\]\]")


def extract_wikilinks(content: str) -> list[str]:
    """Return all [[WikiLink]] targets found in `content`.

    Strips optional alias (anything after `|`). Skips `![[...]]` image embeds.
    """
    return [m.group(1).strip() for m in _WIKILINK_RE.finditer(content)]


def all_wiki_pages() -> list[Path]:
    """Return all wiki .md files (excluding index/log/lint-report/health-report).

    Returned paths are absolute (REPO_ROOT-anchored).
    """
    excluded = {"index.md", "log.md", "lint-report.md", "health-report.md", "_semantic_lint_context.md"}
    if not WIKI_DIR.exists():
        return []
    return sorted(p for p in WIKI_DIR.rglob("*.md") if p.name not in excluded)


def load_allowed_raw_dirs() -> set[str]:
    """Return the set of allowed Raw/ subdirectory names (lowercase).

    Reads from Tools/.raw_dirs if it exists (one name per line, written by
    bootstrap when the user customises Raw/ layout). Falls back to the
    default four directories so the function always returns a usable set.

    Example Tools/.raw_dirs content:
        Sources
        Thoughts
        Records
        Assets
        Academia
    """
    raw_dirs_file = TOOLS_DIR / ".raw_dirs"
    if raw_dirs_file.exists():
        names = [
            line.strip().lower()
            for line in raw_dirs_file.read_text(encoding="utf-8").splitlines()
            if line.strip() and not line.strip().startswith("#")
        ]
        if names:
            return set(names)
    # Default whitelist — matches AGENTS.md §二 default layout
    return {"sources", "thoughts", "records", "assets"}


def resolve_wikilink(name: str) -> list[Path]:
    """Resolve a [[WikiLink]] target to matching wiki page Paths.

    This is the canonical resolver used by both health.py and lint.py.
    Supports:
      - Vault-absolute:  [[Wiki/concepts/Foo]]  → Wiki/concepts/Foo.md
      - Relative:        [[concepts/Foo]]        → Wiki/concepts/Foo.md
      - Stem-only:       [[Foo]]                 → any Wiki/**/*.md whose stem matches
      - Raw/ markers:    [[Raw/...]]             → [] (provenance citations, not navigable)

    Returns a (possibly empty) list of absolute Paths.
    """
    # Skip Raw/ provenance markers — they are citations, not navigable links
    if name.startswith("Raw/") or name.startswith("raw/"):
        return []

    # Strip vault-absolute "Wiki/" prefix for resolution
    link = name.removeprefix("Wiki/").removeprefix("wiki/")

    candidates: list[Path] = []
    for p in all_wiki_pages():
        rel = p.relative_to(WIKI_DIR).as_posix()          # e.g. "concepts/Foo.md"
        stem = rel.removesuffix(".md")                     # e.g. "concepts/Foo"
        if link == rel or link == stem:
            candidates.append(p)
        elif p.stem.lower() == link.lower() or p.stem == link:
            candidates.append(p)
    return candidates


def append_log(entry: str) -> None:
    """Prepend a new entry to wiki/log.md (most-recent-first).

    Caller is responsible for the entry's content, including any leading
    `## [YYYY-MM-DD] ...` header line.
    """
    existing = read_file(LOG_FILE)
    body = entry.strip() + "\n\n" + (existing.lstrip("\n") if existing else "")
    write_file(LOG_FILE, body)


# ─────────────────────────────────────────────────────────────────────
# Hashing
# ─────────────────────────────────────────────────────────────────────
def _hash_hex(content: str) -> str:
    """SHA-256 hex digest of a string."""
    if isinstance(content, str):
        content = content.encode("utf-8")
    return hashlib.sha256(content).hexdigest()


def sha256_short(content: str) -> str:
    """First 8 hex chars of SHA-256 — useful for short cache keys."""
    return _hash_hex(content)[:8]


def sha256_full(content: str) -> str:
    """Full 64-char SHA-256 hex digest."""
    return _hash_hex(content)


# ─────────────────────────────────────────────────────────────────────
# LLM wrapper
# ─────────────────────────────────────────────────────────────────────
def call_llm(
    prompt: str,
    *args: Any,
    model: str | None = None,
    system: str | None = None,
    timeout: int = 600,
    max_tokens: int | None = None,
    exit_on_error: bool = True,
    **kwargs: Any,
) -> str:
    """Invoke an LLM and return the response text.

    Tries (in order):
      1. `opencode` CLI on PATH (the project's own agent)
      2. `claude` CLI on PATH (Claude Code)
      3. `qmd` CLI on PATH (last-resort, primarily a retrieval tool)
      4. If `exit_on_error=False`, returns a placeholder string instead of
         raising NotImplementedError.

    To wire up a real backend, set the `LLM_BACKEND` env var to a CLI
    command template, e.g. `LLM_BACKEND="opencode -m {model}"`. Otherwise
    the default chain above is used.

    Parameters
    ----------
    prompt : str
        The user prompt.
    *args : Any
        Backward-compat positional placeholders. Older callers passed
        (env_var_name, default_model) as positional args; we read the env
        var to honor that contract.
    model : str, optional
        Model identifier (forwarded to the CLI if it supports --model/-m).
    system : str, optional
        System prompt (forwarded as --system if the CLI supports it).
    timeout : int
        Subprocess timeout in seconds (default 10 min).
    max_tokens : int, optional
        Reserved for backends that support it (currently not forwarded).
    exit_on_error : bool
        If True (default), raise NotImplementedError on missing backend.
        If False, return a placeholder string starting with
        "> API call failed: " or "> Semantic lint skipped: ".
    **kwargs : Any
        Reserved for future flags (e.g. temperature).
    """
    # Honor legacy positional signature: (prompt, env_var, default_model)
    if args and model is None:
        env_var = args[0]
        if isinstance(env_var, str):
            model = os.environ.get(env_var) or (args[1] if len(args) > 1 else None)

    backend = os.environ.get("LLM_BACKEND", "").strip()
    candidates: list[list[str]] = []

    if backend:
        tokens = backend.split()
        candidates.append(tokens)
    else:
        m_flag = ["-m", model] if model else []
        s_flag = ["--system", system] if system else []
        candidates.append(["opencode", *m_flag, "run", *s_flag, prompt])
        candidates.append(["claude", *m_flag, *s_flag, prompt])
        candidates.append(["qmd", "ask", prompt])

    last_err: Exception | None = None
    for cmd in candidates:
        exe = cmd[0]
        if shutil.which(exe) is None:
            continue
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=timeout,
                encoding="utf-8",
                errors="replace",
            )
            if proc.returncode == 0:
                return proc.stdout.strip()
            last_err = RuntimeError(
                f"{exe} exited {proc.returncode}: {proc.stderr.strip()[:200]}"
            )
        except (FileNotFoundError, subprocess.TimeoutExpired) as e:
            last_err = e
            continue

    msg = (
        "no LLM backend available. "
        "Install `opencode` or `claude` CLI, or set LLM_BACKEND env var. "
        f"Last error: {last_err}"
    )
    if exit_on_error:
        raise NotImplementedError(f"call_llm(): {msg}")
    return f"> API call failed: {msg}\n"


# ─────────────────────────────────────────────────────────────────────
# Self-test (run `python Tools/common.py` to verify)
# ─────────────────────────────────────────────────────────────────────
if __name__ == "__main__":
    init_env()
    print(f"REPO_ROOT   = {REPO_ROOT}")
    print(f"WIKI_DIR    = {WIKI_DIR}  exists={WIKI_DIR.exists()}")
    print(f"RAW_DIR     = {RAW_DIR}   exists={RAW_DIR.exists()}")
    print(f"GRAPH_DIR   = {GRAPH_DIR} exists={GRAPH_DIR.exists()}")
    print(f"LOG_FILE    = {LOG_FILE}")
    print(f"INDEX_FILE  = {INDEX_FILE}")
    pages = all_wiki_pages()
    print(f"wiki pages  = {len(pages)}")
    print(f"sha256_short('hi') = {sha256_short('hi')}")
    print(f"sha256_full('hi')  = {sha256_full('hi')}")
    print(f"wikilinks  = {extract_wikilinks('see [[Foo]] and [[Bar|alias]]')}")
    print("common.py OK")
